This Jupyter Notebook merge all the columns analysis together.
The columns including:
- satisfaction_level
- last_evaluation
- number_project
- average_monthly_hours
- time_spend_company
- Work_accident
- left
- promotion_last_5years
- department
- salary

## Import package

In [1]:
import pandas as pd
import numpy as np

## Load data

In [2]:
## load data
df = pd.read_csv('./data/HR.csv')

In [3]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

# Satisfaction Level的分析

In [4]:
sl_s = df['satisfaction_level']

In [5]:
## check is there null value
sl_s.isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
14972    False
14973    False
14974    False
14975    False
14976    False
14977    False
14978    False
14979    False
14980    False
14981    False
14982    False
14983    False
14984    False
14985    False
14986    False
14987    False
14988    False
14989    False
14990    False
14991    False
14992    False
14993    False
14994    False
14995    False
14996    False
14997    False
14998    False
14999     True
15000     True
15001    False
Name: satisfaction_level, Length: 15002, dtype: bool

In [6]:
## select the null value
sl_s[sl_s.isnull()]

14999   NaN
15000   NaN
Name: satisfaction_level, dtype: float64

In [7]:
## check the detail of these null value
df[df['satisfaction_level'].isnull()]

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

Than we can drop null or fill null, using `dropna()` or `fillna()`

In [8]:
## drop the null value
sl_s = sl_s.dropna()

To cal mean, std, max, min, median, quantile

In [9]:
## cal mean
sl_s.mean()

0.6128393333333343

In [10]:
## cal std
sl_s.std()

0.24862338135945417

In [11]:
## cal max
sl_s.max()

1.0

In [12]:
## cal min
sl_s.min()

0.09

In [13]:
## cal median
sl_s.median()

0.64

In [14]:
## cal quantile
sl_s.quantile(q=0.25)

0.44

In [15]:
## cal quantile
sl_s.quantile(q=0.75)

0.82

By `skew()`, we can find that mean is small than median

In [16]:
## cal skew
sl_s.skew()

-0.47643761717258093

In [17]:
## cal kurt
sl_s.kurt()

-0.6706959323886252

In [18]:
np.histogram(sl_s.values, bins=np.arange(0.0, 1.1, 0.1))

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

# LastEvaluation的分析

In [19]:
le_s = df['last_evaluation']

## Check outlier

the `le_s` is no null value

In [20]:
## check is there null value
le_s[le_s.isnull()]

Series([], Name: last_evaluation, dtype: float64)

To cal mean, std, max, min, median, quantile

In [21]:
## cal mean
le_s.mean()

67.37373216904412

In [22]:
## cal std
le_s.std()

8164.407523745649

In [23]:
## cal median
le_s.median()

0.72

In [24]:
## cal max
le_s.max()

999999.0

In [25]:
## cal min
le_s.min()

0.36

By `skew()`, we can find that mean is large than median

In [26]:
## cal skew
le_s.skew()

122.48265175204614

In [27]:
## cal kurt
le_s.kurt()

15001.999986807796

In [28]:
## check the value large than 1
le_s[le_s > 1]

15000    999999.0
Name: last_evaluation, dtype: float64

In [29]:
le_s = le_s[le_s<1]

In [30]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
5        0.50
6        0.77
7        0.85
9        0.53
10       0.54
11       0.81
12       0.92
13       0.55
14       0.56
15       0.54
16       0.47
17       0.99
18       0.51
19       0.89
20       0.83
21       0.55
22       0.95
23       0.57
24       0.53
25       0.92
26       0.87
27       0.49
28       0.46
29       0.50
30       0.62
         ... 
14971    0.45
14972    0.97
14973    0.52
14974    0.54
14975    0.79
14976    0.47
14977    0.85
14978    0.47
14979    0.93
14980    0.89
14981    0.93
14982    0.49
14983    0.84
14984    0.56
14985    0.99
14986    0.85
14987    0.70
14988    0.55
14989    0.57
14990    0.88
14991    0.81
14992    0.48
14993    0.83
14994    0.57
14995    0.48
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 14718, dtype: float64

In [31]:
## use quantile to filter the outliers
le_s = df['last_evaluation']

## cal quantile
q_low = le_s.quantile(q=0.25)
q_high = le_s.quantile(q=0.75)

q_interval = q_high - q_low
k = 1.5

In [32]:
le_s = le_s[le_s<q_high+k*q_interval][le_s>q_low-k*q_interval]

In [33]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
5        0.50
6        0.77
7        0.85
8        1.00
9        0.53
10       0.54
11       0.81
12       0.92
13       0.55
14       0.56
15       0.54
16       0.47
17       0.99
18       0.51
19       0.89
20       0.83
21       0.55
22       0.95
23       0.57
24       0.53
25       0.92
26       0.87
27       0.49
28       0.46
29       0.50
         ... 
14971    0.45
14972    0.97
14973    0.52
14974    0.54
14975    0.79
14976    0.47
14977    0.85
14978    0.47
14979    0.93
14980    0.89
14981    0.93
14982    0.49
14983    0.84
14984    0.56
14985    0.99
14986    0.85
14987    0.70
14988    0.55
14989    0.57
14990    0.88
14991    0.81
14992    0.48
14993    0.83
14994    0.57
14995    0.48
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [34]:
len(le_s)

15001

In [35]:
np.histogram(le_s.values, bins=np.arange(0.0, 1.0, 0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 3065]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [36]:
le_s.mean()

0.7160675954936238

In [37]:
le_s.std()

0.17118464250786247

In [38]:
le_s.median()

0.72

# NumberProject的分析

In [39]:
np_s = df['number_project']

## Check outlier

the `le_s` is no null value

In [40]:
## check is there null value
np_s[np_s.isnull()]

Series([], Name: number_project, dtype: int64)

To cal mean, std, max, min, median, quantile

In [41]:
## cal mean
np_s.mean()

3.8026929742700974

In [42]:
## cal std
np_s.std()

1.2327327792005955

In [43]:
## cal median
np_s.median()

4.0

In [44]:
## cal max
np_s.max()

7

In [45]:
## cal min
np_s.min()

2

By `skew()`, we can find that mean is large than median

In [46]:
## cal skew
np_s.skew()

0.3377744235231047

In [47]:
## cal kurt
np_s.kurt()

-0.49580962709450604

In [48]:
## count the value appear
np_s.value_counts()

4    4365
3    4055
5    2761
2    2391
6    1174
7     256
Name: number_project, dtype: int64

In [49]:
## or check the percentage of the value
np_s.value_counts(normalize=True)

4    0.290961
3    0.270297
5    0.184042
2    0.159379
6    0.078256
7    0.017064
Name: number_project, dtype: float64

In [50]:
## sort the result by the index
np_s.value_counts(normalize=True).sort_index()

2    0.159379
3    0.270297
4    0.290961
5    0.184042
6    0.078256
7    0.017064
Name: number_project, dtype: float64

# AverageMonthlyHours的分析

In [51]:
amh_s = df['average_monthly_hours']

## Check outlier

the `le_s` is no null value

In [52]:
## check is there null value
amh_s[amh_s.isnull()]

Series([], Name: average_monthly_hours, dtype: int64)

To cal mean, std, max, min, median, quantile

In [53]:
## cal mean
amh_s.mean()

201.0417277696307

In [54]:
## cal std
amh_s.std()

49.94181527437911

In [55]:
## cal median
amh_s.median()

200.0

In [56]:
## cal max
amh_s.max()

310

In [57]:
## cal min
amh_s.min()

96

By `skew()`, we can find that positve skewness

In [58]:
## cal skew
amh_s.skew()

0.05322458779916304

In [59]:
## cal kurt
amh_s.kurt()

-1.1350158577565719

In [60]:
amh_s = amh_s[amh_s<amh_s.quantile(0.75) + 1.5*(amh_s.quantile(0.75) - amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25) - 1.5*(amh_s.quantile(0.75) - amh_s.quantile(0.25))]

In [61]:
len(amh_s)

15002

In [62]:
np.histogram(amh_s.values, bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324]),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [63]:
np.histogram(amh_s.values, bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86]),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))

In [64]:
amh_s.value_counts(bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

# TimeSpendCompany的分析

In [65]:
tsc_s = df['time_spend_company']

In [66]:
tsc_s.value_counts().sort_index()

2     3245
3     6445
4     2557
5     1473
6      718
7      188
8      162
10     214
Name: time_spend_company, dtype: int64

In [67]:
## cal mean
tsc_s.mean()

3.498066924410079

# WorkAccident的分析

In [68]:
amh_s = df['average_monthly_hours']

## Check outlier

the `le_s` is no null value

In [69]:
## check is there null value
amh_s[amh_s.isnull()]

Series([], Name: average_monthly_hours, dtype: int64)

To cal mean, std, max, min, median, quantile

In [70]:
## cal mean
amh_s.mean()

201.0417277696307

In [71]:
## cal std
amh_s.std()

49.94181527437911

In [72]:
## cal median
amh_s.median()

200.0

In [73]:
## cal max
amh_s.max()

310

In [74]:
## cal min
amh_s.min()

96

By `skew()`, we can find that positve skewness

In [75]:
## cal skew
amh_s.skew()

0.05322458779916304

In [76]:
## cal kurt
amh_s.kurt()

-1.1350158577565719

In [77]:
amh_s = amh_s[amh_s<amh_s.quantile(0.75) + 1.5*(amh_s.quantile(0.75) - amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25) - 1.5*(amh_s.quantile(0.75) - amh_s.quantile(0.25))]

In [78]:
len(amh_s)

15002

In [79]:
np.histogram(amh_s.values, bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324]),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [80]:
np.histogram(amh_s.values, bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86]),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))

In [81]:
amh_s.value_counts(bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

# Left的分析

In [82]:
l_s = df['left']

In [83]:
l_s.value_counts()

0    11428
1     3574
Name: left, dtype: int64

There is no outlier.

# PromotionLast5Years 的分析

In [84]:
pl5y_s = df['promotion_last_5years']

In [85]:
pl5y_s.value_counts().dropna()

0    14683
1      319
Name: promotion_last_5years, dtype: int64

There is no outliers.

# Salary 的分析

In [86]:
s_s = df['salary']

In [87]:
s_s.value_counts()

low       7318
medium    6446
high      1237
nme          1
Name: salary, dtype: int64

Drop the outlier

In [88]:
s_s = s_s.where(s_s!='nme').dropna()

# Department的分析

In [89]:
d_s = df['department']

In [90]:
d_s.value_counts(normalize=True)

sales          0.275963
technical      0.181309
support        0.148647
IT             0.081789
product_mng    0.060125
marketing      0.057192
RandD          0.052460
accounting     0.051127
hr             0.049260
management     0.041994
sale           0.000133
Name: department, dtype: float64

Find that "sale" vs "sales". In the real problem, how to handle the outlier need to according to the business.

In [91]:
# drop the sale
d_s = d_s.where(d_s!='sale').dropna()