## Import package

In [1]:
import pandas as pd
import numpy as np

## Load data

In [2]:
## load data
df = pd.read_csv('./data/HR.csv')

In [3]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
14972                0.11             0.97               6   
14973                0.36             0.52               2   
14974                0.36             0.54               2   
14975                0.10             0.79               7   
14976                0.40             0.47               2   
14977                0.81             0.85               4   
14978                0.40             0.47               2   
14979                0.09             0.93               6   
14980                0.76             0.89               5   
14981                0.73             0.93               5   
14982                0.38             0.49               2   
14983                0.72             0.84               5   
14984                0.40             0.56               2   
14985                0.91             0.99               5   
14986                0.85             0.85               4   
14987                0.90             0.70               5   
14988                0.46             0.55               2   
14989                0.43             0.57               2   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14992                0.40             0.48               2   
14993                0.76             0.83               6   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   
15001                0.70             0.40               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
0                        157                   3              0     1   
1               

select the column

In [4]:
amh_s = df['average_monthly_hours']

## Check outlier

the `le_s` is no null value

In [5]:
## check is there null value
amh_s[amh_s.isnull()]

Series([], Name: average_monthly_hours, dtype: int64)

To cal mean, std, max, min, median, quantile

In [6]:
## cal mean
amh_s.mean()

201.0417277696307

In [7]:
## cal std
amh_s.std()

49.94181527437911

In [8]:
## cal median
amh_s.median()

200.0

In [9]:
## cal max
amh_s.max()

310

In [10]:
## cal min
amh_s.min()

96

By `skew()`, we can find that positve skewness

In [11]:
## cal skew
amh_s.skew()

0.05322458779916304

In [12]:
## cal kurt
amh_s.kurt()

-1.1350158577565719

In [13]:
amh_s = amh_s[amh_s<amh_s.quantile(0.75) + 1.5*(amh_s.quantile(0.75) - amh_s.quantile(0.25))][amh_s>amh_s.quantile(0.25) - 1.5*(amh_s.quantile(0.75) - amh_s.quantile(0.25))]

In [14]:
len(amh_s)

15002

In [15]:
np.histogram(amh_s.values, bins=10)

(array([ 367, 1240, 2736, 1722, 1628, 1712, 1906, 2240, 1127,  324]),
 array([ 96. , 117.4, 138.8, 160.2, 181.6, 203. , 224.4, 245.8, 267.2,
        288.6, 310. ]))

In [17]:
np.histogram(amh_s.values, bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(array([ 168,  171,  147,  807, 1153, 1234, 1075,  824,  818,  758,  751,
         738,  856,  824,  987, 1002, 1045,  935,  299,  193,  131,   86]),
 array([ 96, 106, 116, 126, 136, 146, 156, 166, 176, 186, 196, 206, 216,
        226, 236, 246, 256, 266, 276, 286, 296, 306, 316]))

In [18]:
amh_s.value_counts(bins=np.arange(amh_s.min(), amh_s.max()+10, 10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64